### ISSUE TITLE
sacred opt changed

### ISSUE THREAD

**Issue by millawell** [automl/labwatch#6]
Since this commit:
https://github.com/IDSIA/sacred/commit/216549ca325439013b7f9225346facd074ee3a82#diff-9c6482f0e6fd19199727a4946e5d74f7

`opt.has_pymongo` is no longer existent.

which yields to the following error when running some labwatch experiment:

```Traceback (most recent call last):
  File "experiment.py", line 6, in <module>
    from labwatch.assistant import LabAssistant
  File "/local/lib/python3.4/site-packages/labwatch/__init__.py", line 4, in <module>
    from labwatch.assistant import LabAssistant
  File "/local/lib/python3.4/site-packages/labwatch/assistant.py", line 25, in <module>
    if not opt.has_pymongo:
AttributeError: 'module' object has no attribute 'has_pymongo'

**Comment by abojchevski** [comment]
+1

**Comment by basveeling** [comment]
Likewise for installation, adding the following line to sacred/optional.py solves this:
has_pymongo = modules_exist('pymongo')
